# Generated by Django 6.0.2 on 2026-02-23 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('elo_rating', models.IntegerField(default=1200)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('joined_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-elo_rating'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('round_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('white_wins', 'White Wins'), ('black_wins', 'Black Wins'), ('draw', 'Draw')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('player_black', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_black', to='club.member')),
                ('player_white', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_white', to='club.member')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='EloHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_before', models.IntegerField()),
                ('rating_after', models.IntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_changes', to='club.match')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_history', to='club.member')),
            ],
            options={
                'verbose_name_plural': 'ELO Histories',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
