# Generated by Django 6.0.2 on 2026-05-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='lichess_token',
            field=models.CharField(blank=True, help_text='Personal Lichess API token (lichess.org/account/oauth/token). Optional — only needed for higher rate limits or accessing private studies.', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='lichess_username',
            field=models.CharField(blank=True, help_text='Your public Lichess username, used to fetch your games for analysis.', max_length=30),
        ),
    ]
